### ISSUE TITLE
`xxx_update` naming scheme for lsm_volume_ident_led_set()

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#128]
Should we change `lsm_volume_ident_led_set()` to `lsm_volume_ident_led_on()` and `_off()`?

**Comment by joehandzik** [comment]
So, the reason why I went with _set and _clear is because those are the terms that sg_ses uses: http://sg.danny.cz/sg/sg_ses.html#mozTocId57479

My expectation is that most people who use these APIs will be familiar with that tool, so I chose a familiar name. We can easily change to _on and _off if folks are in favor of that. Thoughts, @tasleson? Or @BlaineEXE?

**Comment by tasleson** [comment]
@joehandzik @cathay4t In this specific case `on` and `off` would be good as it logically makes sense for something that illuminates.

**Comment by joehandzik** [comment]
@tasleson Sounds fair, I'll submit a pull today to change them.

**Comment by joehandzik** [comment]
@tasleson @cathay4t Closing this out, fixed in PR #130
