### ISSUE TITLE
lsm doesn't work on python 3 if a build goes into a non "python3" directory

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#208]
I was hoping it wasn't this simple, but...

In my debian environment, python 3.4 was also installed. For whatever reason (haven't really looked), PR #103 or some artifact of the way python3 works installed all the python3 code into /usr/lib/python3.4/site-packages/lsm. Nothing worked (failed at 'lsmcli' on the lsm import), so I copied the entire lsm directory from /usr/lib/python3.4/site-packages/ to /usr/lib/python3/dist-packages/.

lsmcli works now. So, is that "intended behavior", or a bug?

**Comment by tasleson** [comment]
@joehandzik Did you do a `make install` or a dep pkg install?

**Comment by cathay4t** [comment]
This is caused by another Debian special stuff:
http://stackoverflow.com/questions/9387928/whats-the-difference-between-dist-packages-and-site-packages

The autotools we are using install python things to site-packages. 

But it was supposed to works well in both `site-packages` and `dist-packages`.

@joehandzik Which Debian version are you using? I would like to try it from my end. And what's the output of this command `python3 -c 'import site; print(site.getsitepackages())'`

**Comment by joehandzik** [comment]
@cathay4t Sorry for the delay on this, still don't have all the data (couldn't get at the system for the 'python3 -c' output yet, having lab issues). I'm using Debian Jessie across the board for my testing.

**Comment by cathay4t** [comment]
OK. The python search path in debian 8 is:
```
fge@deb:~$ python3 -c 'import site; print(site.getsitepackages())'
['/usr/local/lib/python3.4/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.4/dist-packages', '/usr/lib/dist-python']
```

Which does not include `site-packages`. Will investigate workaround for autotools.

**Comment by cathay4t** [comment]
On debian 8, the automake m4 file `/usr/share/aclocal-1.14/python.m4` is using this command to check python site path:
```bash
python3 -c "import sysconfig; print(sysconfig.get_path('platlib', vars={'platbase':'/usr'}))"
```
which produce the incorrect path: `/usr/lib/python3.4/site-packages`.

So it's a bug of python3 in debian. I failed to find any bug created in debian, but found one in [Ubuntu] [1] with identical issue, I could use some help from debian experts to report this bug to debian.

[1]: https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092

**Comment by joehandzik** [comment]
@cathay4t Yeah, doubtful that we'd get a fix in any reasonable amount of time. @rickysarraf would be the person I'd suggest to shepherd us through the process here...if he doesn't respond here I'll ping him tomorrow via email and copy you.

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Thu, 2016-09-22 at 08:53 -0700, Joe Handzik wrote:
> @cathay4t Yeah, doubtful that we'd get a fix in any reasonable amount of time.
> @rickysarraf would be the person I'd suggest to shepherd us through the
> process here...if he doesn't respond here I'll ping him tomorrow via email and
> copy you.

Please get it reported first[1]. If you have your Debian setup in place, please
use it to report the bug. The default tool to report bugs, in Debian, is
reportbug.


As for the fix, you need to get it fixed in Unstable first, if it still applies
to Unstable. And then you need to backport the fix to Stable, and then ask the
package maintainer (for Python, it should be a team, even though it only lists a
couple of folks as its Maintainers) to propose its inclusion for Stable.


[1] https://www.debian.org/Bugs/Reporting
[2] https://wiki.debian.org/StableProposedUpdates

- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJX5ARPAAoJEKY6WKPy4XVpz1YQAIH+O+ozCyHFJRelfIYKEcd6
8huZONsgFYMA0jiN71Xxa07SxK8bgMqx7lxzR1yLT2BcjUHI+e3u2VF8POarPvwm
Z4JU8bby2jFK76cxZVmt+V83AAWbdcAMeoRzgqsKq1RmTjbCvplp+BAvtSelXqpc
NGDavgDvbDxUkSLhSoxOHfR2+D3CU+LEXWpuxn443k7BvNaFtYf1Y+xcdOrxnDfd
WQMOYnL67Q+bt+wmlXrJw21HfI7VuWa1LB81WAEwHOJ2kwC6QqcDUOutzlY9NseE
z97mxS8pV7jooBCB8upR+Sw0hRvY/pQh5oU0B9FxL2N/Lmo52bzmkAwBKRAcc/Qw
gczKcVQ+k/JdoIZvsluWGDb+83IjfOia81qUdOHB6trdlFZFKltqcs3ib1ua4QjE
THUa5lamcSaDEbE+yiIdlIGmmgGarZrKMP235ZJfjHcGQJB3TAPCinU61eDZP8d6
2mbcdwtoPoEGBoiO3Nm0yn2JDIrnsrrdzbqa7qgXN8lUDHQBV07fH1fehvXKtCxh
XWYo7b48Z+5Ts0/lzLC3rULU//efwHID00Mav+l9i9+OiCK6EPEaIuYSSjUQC6gX
IOmkbPrxMdKJMi34tPw+mZQM+uYFzjUymHP04QGd1xMKaFbNg+3Lbcypld8EoTbq
03KjYfSrmG8lQa8WfU0s
=cZZf
-----END PGP SIGNATURE-----

**Comment by tasleson** [comment]
Is this something we can mitigate with a deb packaging work around?  If `make install` is placing the files in the incorrect location, can't we work around that when packaging?  I'm not familiar with how deb packaging works, so maybe this isn't an option.

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Thu, 2016-09-22 at 09:41 -0700, Tony Asleson wrote:
Is this something we can mitigate with a deb packaging work around?  If make install is placing the files in the incorrect location, can't we work around that when packaging?  I'm not familiar with how deb packaging works, so maybe this isn't an option.

Yes. The packaging tools have provision for it.
https://www.debian.org/doc/manuals/maint-guide/dother.en.html#install

Is it the libstoragemgmt package suffering this problem?
Or is it the python package itself ?

For either one, please file a bug report with the proposed fix against the
respective package.

PS: BTW, The Ubuntu bug that has been referenced, does not have any closure

- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJX5A1TAAoJEKY6WKPy4XVpEhMQAKgN10JdnG0guOlSr9h8j9Cx
XrnyTVB+udOr+cSMPw//DtC69Q25sKWcEU9qZZmSI3rt5tTzO8RNQ/pjyu7+xPy6
9pSXPYhufY7YxwvBAamMvX+YTiHeqHd8BUWGo1zx2FEp1h1l1ObmqHlzu0K+c3ib
HuazPJEXjiFPr5jAYjLp9MYeh8pW+lK2R+nwkIGFJeXdKCmm00si/fZRo0/0DDff
+m8btI/3+Ofego7lureRUnC1x7Fj7ksPF/Hq1FWFTiI/4+u9+fFK57JzmAgLr5T3
+aK9YYJF7QK1xGdklD0rKIaZOke0qgX5wh3ybG8szdaZm5b53IzdD5acJy5ajZd1
YfnVsZOkP1+SaxR4R+GNvF+LCJBadFmGiMrW30hKOtQrWaBelWm0Q1/tvC47eeN9
QFIWeKtuDgUxsvhjDw9gQOHubMa2kH02E5VMitcsH2kmte5wEgvd4y861FkVlnSr
D8AyseFuIQRQSvy2VJ4nrToZh02a7+Qtnwtng+bo05prPHJvKuYjy1nOA8MPMZlJ
e30P2r3bEJtowfEDxI5pKEUKFX6aKXVhPZ7/QJ7UWD3aQTtCD/esLeYQv4twySWy
Y4lD6ypHDoswtFFg391u4mE3mGno85eXM3jX4nMiVwWLEzBcA9fZxg3+14R9eXle
0ECuC67EUhRn2aHUuOfm
=+yhN
-----END PGP SIGNATURE-----

**Comment by joehandzik** [comment]
@rickysarraf Yeah, I figured it would be possible to do in packaging. I guess this will just continue to be a minor annoyance for me when I build and install from source.

The symptom will be that installing via a .deb without implementing a workaround wouldn't put files in the place that Debian is (incorrectly) expecting them. So the bug is in Debian from our perspective, but would manifest for our users.

**Comment by cathay4t** [comment]
I will take a thorough investigation and report a bug to debian.

Still no luck for a workaround in configure.ac.

**Comment by cathay4t** [comment]
Debian bug reported:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839064

The debian stable/testing/unstable are all impacted.

**Comment by cathay4t** [comment]
@joehandzik Could you try patch in https://github.com/cathay4t/libstoragemgmt/commit/ccb382f66b0ce3c72cdac86829b8b566aa04b0be along with tony's PR?

It works on my debian 8.6.

**Comment by joehandzik** [comment]
@cathay4t Looks good to me, just tested. Closing now.
