### ISSUE TITLE
HPSA plugin: Got system status info as `status=[OK]status=[OK]status=[OK]`

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#212]
* When everything is OK, no status_info should be provided.
* Better version could be `Controller Status=xxx, Cache Status=xxx, Battery/Capacitor Status=xxx`.

**Comment by joehandzik** [comment]
Guess that went in here: https://github.com/libstorage/libstoragemgmt/commit/021b29b830d1b2c1f89d5cf1ffcf8b2d94bee782

@BlaineEXE, any thoughts about how to maintain your desired result and conform to what @cathay4t said above? My guess would be to prepend the 'key_name' element onto the string addition that you're making to start. From there, is there any particular reason why you need to have the status_info, even in success cases?

**Comment by BlaineEXE** [comment]
Prepending the key name makes sense, and that seems the mostly likely place where the bug was inserted.
As for why do it in success csaes, the property is called `status_info`, not `failure_info`. If this isn't populated in some cases but is populated in others, we are effectively doing the same thing as HPSSACLI when they decide not to show property fields when they're irrelevant.
