### ISSUE TITLE
[RFC] Merging local HBA RAID plugins.

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#238]
Initial ideas:
 * Create a plugin named as `local` to hold code of `hpsa` and `megaraid` plugins.
 * Searching PCI devices which use `hpsa` and `megaraid` driver via sysfs[1].
 * Add support of SCSI enclosure.
 * Raise `INVALID_ARGUMENT` error on missing `hpssacli` or `storecli` tools at plugin register. 
   URI parameter `ignore_missing_bin=true` may disable this.

Updates:
 * Keep both `local` plugin and independent plugin. 
 * `local` plugin just a wrap of independent plugin and a place where certain action require cross plugins cooperation..
 * Support of linux local NFS server and client. Of course, we need to create a independent plugin `nfs` first.
 * Expand to support LVM, LIO iSCSI/FCoE and etc.

[1]: lspci is using link path of `/sys/devices/pci0000:80/0000:80:02.0/0000:81:00.0/driver`. A better way may be read the content of folder `/sys/module/megaraid_sas/drivers/pci:megaraid_sas`

**Comment by joehandzik** [comment]
@cathay4t This looks like a good start. I think that we should allow both independent plugins to exist as well, in case a user knows they don't want to see an error anytime storcli or ssacli is not installed. Not sure that I like the ignore_missing_bin idea to be the only way to avoid that error message. Though maybe there could be a single plugin named local, and the logic could be:

local:// - require both binaries
hpsa:// - require ssacli only
megaraid:// - require megaraid only

This would maintain backwards compatibility with existing code (we have released code for Lustre using lsm, and Scality has released code as well).

I'll need to take a look to see if there's a best practice method to identify that a PCI device uses either particular driver. Also, keep in mind that in Gen10 Smart Array will use a new driver (I forget the name of it, but I can be tasked with making sure that critical piece doesn't slip through the cracks).

**Comment by cathay4t** [comment]
I like the idea of keep both independent and all-in-one plugins.
One trivial change is `local:// - require certain binaries if supported RAID card found.`

**Comment by jumitche** [comment]
Features like NFS exporting will use the same code for any of the 'local system' drivers, be that hpsa, megaraid, lvm, or none of the above.  Would it be better to have a plugin that does only the nfs features, and have the user need to open it seperately, or can there be some kind of virtual/common plugin, where the same features, calling the same one set of code, can appear in multiple plugins ?

**Comment by joehandzik** [comment]
@jumitche I'm wondering if there are some unannounced things that I don't know about behind your comment (the use of "NFS exporting" and "will" in the same sentence imply to me that that's an upcoming feature :) ), but I will point out that we started building the lsm_local_disk_* commands this year, which use SCSI/ATA/NVMe standards to communicate with disks that are exposed to the host. Those APIs can actually be used within the existing plugins, so in a way we have common features that can appear in multiple plugins already. So, ideally, we'd be able to extend those APIs and implement whatever you need within that existing set of commands.

Does that help get to the root of your question in any way? Apologies if I misunderstood anything!

**Comment by jumitche** [comment]
@joehandzik sorry, bad choice of language, i blame too many years working in closed shops :)

What i was trying to get at is that libstoragemgmt already supports setting up of nfs exports for its plugins right, but at the moment that is only supported by a subset of them, and notably by none of the 'local' raid controller plugins, I was proposing to add that missing support to those plugins, with the view to then enhance the feature with support for kerberized nfs exports.

As there is more than one plugin that could use the same code to achieve that, I was wondering what opinions there were on the right way to go about such code sharing between them?

If it affects the answer, the kerberization code involves a fair bit of cli calling and output parsing, and already exists as a standalone python script. for the exports file handling i believe there is example python code in targetd, but it could probably equally well be written in C

**Comment by joehandzik** [comment]
@jumitche Haha, no worries. I understand now (I think).

@tasleson and @cathay4t can correct me if I'm wrong, but any NFS export support is going to be implemented on a plugin-by-plugin basis because that feature is vendor-specific (EMC/Dell SAN nfs exports are not the same code as any other nfs export).

So, we would need to create a vendor-agnostic feature to support that, as you suggest. Right now, our vendor-agnostic code is all storage transport/subsystem-based code (SCSI spec, ATA spec, etc), but I'm not opposed to expanding that to include system calls. So, the design would look similar to any of the lsm_local_disk_* commands that we've created thusfar. Perhaps it would involve creating some new files along the lines of libsys.c/h, though your Red Hat counterparts would definitely have final say on that.

As far as actually getting the work done is concerned, you have two options (once we get a final yea/nay from @cathay4t and/or @tasleson):

1. Go off and put together a PR, and we'll review it once it has been submitted, or
2. Submit a new issue request detailing as much of the design as possible, and someone will get to it when it makes sense from a priority perspective (or someone new to the project and try to implement it).

Obviously you'll have more control with option 1, but I understand if you prefer to go with option 2.

**Comment by cathay4t** [comment]
@jumitche Could you list use cases of NFS? We could find out where we should place the code.

Use case example:
 * Create an folder `/somewhere/foo`
 * Create an NFS export `foo` using folder `/somewhere/foo` with root access, rw access, ro access settings. We have( or don't have) API for this.
 * Change NFS export authentication type to `balala`. We have( or don't have) API for this.

**Comment by jumitche** [comment]
The NFS exporting functionality is already there in several of the plugins, are there no such use cases from the planning of the existing features ?  I was looking just to finish that work and make it available for all the plugins where practical, but the more i look at it the more broken the existing design seems to be, this division of the hosts into arbitrary categories of no_root_squash, ro, rw when those are not mutually exclusive, and the then sharing of other options like sec.

Consider a fairly simple use case then.
* Create a volume on local megaraid card, mkfs and mount as /home
* Export /home to backup.local as read-only, no_root_squash, sec=sys
* Export /home to *.workstation.local as read-write, root_squash, sec=krb5

The current API would seem not to permit that, because of the odd separation of root_squash and ro/rw options, and the shared other options.

Was this part of the API written based off the features of a specific appliances API perhaps ? As it is not a good fit for the actual nfs export capabilities, this is something that might be worth investigating further.

anyway, i digress.

NFS use case via ontap plugin:
* Create Volume 'Home' - Supported
* Create Filesystem '/home' - Supported
* Export Filesystem /home as read-write - Supported

NFS use case via megaraid plugin:
* Create Volume 'Home' - Supported
* Create Filesystems '/home' - Unsupported, needs external mkfs and mount
* Export Filesystem as read-write - Unsupported.

Now these are all steps that have API calls to request them, they just arent supported for all the plugins. I am trying to export support to more of the plugins so that it can be consistent across device types.

**Comment by tasleson** [comment]
> Consider a fairly simple use case then.
>
>    Create a volume on local megaraid card, mkfs and mount as /home
>    Export /home to backup.local as read-only, no_root_squash, sec=sys
>    Export /home to *.workstation.local as read-write, root_squash, sec=krb5
>
>  The current API would seem not to permit that, because of the odd separation of root_squash and
>  ro/rw options, and the shared other options.

I'll take full responsibility for any muck-ups here.  We can certainly add an additional call that removes any deficiencies, but be warned that implementing it across all the different implementations may prove difficult.

**Comment by cathay4t** [comment]
@jumitche
> Create Filesystems '/home' - Unsupported, needs external mkfs and mount

Can this be done by storaged or other library? You may use libstoragemgmt local disk API to find out the newly create volume via `lsm.LocalDisk.vpd83_search()` using the new volume vpd83 property.

> Export Filesystem as read-write - Unsupported.

It seems better fit in to a NFS plugin. Then we use it in local plugin. Any issue you got when adding the new NFS plugin to support this?

**Comment by jumitche** [comment]
I have submitted a pull-request #243 with a first cut of an nfs plugin. 
As a compromise between the multiple-hosts-one-option-set of the api, and the one-host-per-option-set nature of the exports file, any add request with multiple hosts gets split out into one entry per host, so that there is one line in the file for each host+path pairing, that pairing is also used to generate the exportid strings.   Comments please?

**Comment by dwlehman** [comment]
(Chiming in very late) @cathay4t While your proposal here looks good to me, I don't see it as being very high on your priority list unless users other than me would actually be interested in using this.

**Comment by joehandzik** [comment]
@dwlehman For our use cases at HPE, we want this too. It just makes pitching libstoragemgmt easier as a component of the solution when the user can effectively use megaraid and smart array tooling interchangeably under the covers.

**Comment by dwlehman** [comment]
@joehandzik good to know. I agree that it is a nice simplification for users.

**Comment by cathay4t** [comment]
@joehandzik I will draft the POC for this as we seems got enough +1

**Comment by cathay4t** [comment]
PR #288 submitted. Closing.
