### ISSUE TITLE
configure: error: Missing yajl development headers

### ISSUE THREAD

**Issue by joehandzik** [libstorage/libstoragemgmt#35]
When running "./configure --prefix=/usr", I get the error in the title. I'll find the library just fine, but I figured I'd post this up here as an FYI in case this isn't supposed to be a required dependency. If it is, it might be nice to have an install-deps script or something like that.

**Comment by tasleson** [comment]
@joehandzik Just to clarify, when you say you **find the library just fine** is it that you are finding the shared object or that you actually have the header files too?  On a rpm based box you need both yajl and yajl-devel, otherwise you won't have the yajl header files to compile against.  To build from source you need the dependencies outlined here: http://libstorage.github.io/libstoragemgmt-doc/doc/lib_dev_guide.html#1-2-install-build-dependencies

**Comment by joehandzik** [comment]
That's a good point, I should have circled back here. I went through the process of setting this all up without realizing that the link you just pointed me to existed. :( I suppose I was surprised to see how many dependencies there were, and noted that a script to install those would have been an ideal solution from a new user's perspective. I'll close this out.
