### ISSUE TITLE
The `rh_rpm_dependency` does not works on Fedora 29 due to pywbem.

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#373]
The Fedora 29+ only provides `python3-pywbem`.

If we drop  the support of RHEL 7 as developer environment(we already force `make rpm` as Fedora only), we should update `rh_rpm_dependency` to use `python3-pywbem`.

**Comment by cathay4t** [comment]
@tasleson Any idea?

**Comment by cathay4t** [comment]
And python3-devel is missing in `rh_rpm_dependency`

**Comment by tasleson** [comment]
Maybe we should break the package dependencies out for py2 and py3 into separate files?

**Comment by tasleson** [comment]
Possible solution https://github.com/libstorage/libstoragemgmt/pull/389

**Comment by tasleson** [comment]
The `runtests.sh` script when it's run with a configure that has been run with `--with-python3` we test python3 client with python2 plugins and vice-versa.  This has worked because fedora supported everything we need for both py2 and py3, but with the later distributions only having python3 support for the libraries we need, I believe we are going to lose ability to test this combination.

In reality we really shouldn't have users using different run-times for plugins vs client side, so as long as we continue to test the code with python2 on older distributions and python3 on newer I think we can drop the testing for different run-times between client side and plugin side.
