### ISSUE TITLE
tmpfiles: Line references path below legacy directory

### ISSUE THREAD

**Issue by k0ste** [libstorage/libstoragemgmt#514]
Got this on Archlinux with `systemd 251 (251.7-4-arch)`

```python
:: Running post-transaction hooks...
(1/3) Reloading system manager configuration...
(2/3) Creating temporary files...
/usr/lib/tmpfiles.d/libstoragemgmt.conf:1: Line references path below legacy directory /var/run/, updating /var/run/lsm → /run/lsm; please update the tmpfiles.d/ drop-in file accordingly.
/usr/lib/tmpfiles.d/libstoragemgmt.conf:1: Failed to resolve group 'libstoragemgmt'.
/usr/lib/tmpfiles.d/libstoragemgmt.conf:2: Line references path below legacy directory /var/run/, updating /var/run/lsm/ipc → /run/lsm/ipc; please update the tmpfiles.d/ drop-in file accordingly.
/usr/lib/tmpfiles.d/libstoragemgmt.conf:2: Failed to resolve group 'libstoragemgmt'.
error: command failed to execute correctly
```

**Comment by tasleson** [comment]
Are you building and installing from source or using an installation package?

The messages `Line references path below legacy directory /var/run/,...` are caused by the current version in git which still uses old path.  The packaging I do for fedora and EL patch this for newer versions and leave as is for older versions.  I'll submit a PR which updates this so that what's in git better matches the current state of things.

The other issue about `Failed to resolve group 'libstoragemgmt'.` is caused by the system not having a libstoragemgmt group.  This is being handled by the install package for rpm and deb based packaging.  I'm not familiar with arch packaging.

**Comment by k0ste** [comment]
We are build package for Archlinux, the [source of package in AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libstoragemgmt). #515 should resolve this problem, thanks 🙂

**Comment by tasleson** [comment]
#515 Merged, let me know if you would prefer to have me roll a new release to pick this up.

**Comment by k0ste** [comment]
#516
